version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./logs:/var/log

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: halodb
      MYSQL_USER: halodb
      MYSQL_PASSWORD: halodb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PORT: 3306
    # healthcheck:
    #  - test: "mysql -u$$MYSQL_USER -p$$MYSQL_PASSWORD content -e 'select 1'"
    #  - interval: 1s
    #  - retries: 120
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
      - ./data/db_data:/var/lib/mysql
      # - /data/shared/halodb/db_data/data:/var/lib/mysql
