version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      - "8080:5000"
    depends_on:
      - db
    volumes:
      - ./logs:/var/log

  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: halodb
      MYSQL_PASSWORD: halodb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
      - ./data:/var/lib/mysql
