version: '3.4'
services:
  app:
    links:
      - db
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      MYSQL_DATABASE: halodb
      MYSQL_USER: halodb
      MYSQL_PORT: 3306
    volumes:
      - ./volumes/logs:/var/log

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: halodb
      MYSQL_USER: halodb
      MYSQL_PORT: 3306
    user: '1021:1002'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
