version: "2"
services:
  app:
    build: ./api
    links:
      - db
    ports:
      - "8080:5000"
    depends_on:
      - db


  db:
    image: mysql:8.0
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql