services:
  app:
    build:
      context: .
      target: base
    environment:
      APP_ENV: development
      MYSQL_PASSWORD: halodb
    volumes:
      - ./api:/opt/halodb-api/api:ro
      - ./volumes/tmp:/opt/halodb-api/tmp
      - ./volumes/uploads:/opt/halodb-api/uploads

  db:
    environment:
      MYSQL_PASSWORD: halodb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
