services:
  app:
    links:
      - db
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      CREDENTIALS_FILE: /run/secrets/credentials
      MYSQL_DATABASE: halodb
      MYSQL_USER: halodb
      MYSQL_PORT: 3306
      TMPDIR: /opt/halodb-api/tmp
      UPLOADS_DIR: /opt/halodb-api/uploads
    secrets:
      - credentials

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: halodb
      MYSQL_USER: halodb
      MYSQL_PORT: 3306
    user: '1021:1002'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro

secrets:
  credentials:
    file: secrets/credentials.json
