-- MySQL Script generated by MySQL Workbench
-- Thu May 30 09:04:39 2024
-- Model: General    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema halodb
-- -----------------------------------------------------
-- The HaloDB 
DROP SCHEMA IF EXISTS `halodb` ;

-- -----------------------------------------------------
-- Schema halodb
--
-- The HaloDB 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `halodb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `halodb` ;



-- -----------------------------------------------------
-- Table `halodb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `halodb`.`user` ;

CREATE TABLE IF NOT EXISTS `halodb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `uid` VARCHAR(40) NOT NULL COMMENT 'Firebase unique identifier',
  `name` VARCHAR(80) NOT NULL,
  `surname` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL,
  `email` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `registration_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `halodb`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `halodb`.`group` ;

CREATE TABLE IF NOT EXISTS `halodb`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `description` VARCHAR(400) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table `halodb`.`user_has_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `halodb`.`user_has_group` ;

CREATE TABLE IF NOT EXISTS `halodb`.`user_has_group` (
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  `relation` ENUM('owner', 'member', 'invited') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL COMMENT 'Describes the relationship of the user with the group. It can be \'owner\' (the user who has created the group) \'member\' (the user can access to the data, the samples, shared to the group) \'invited\' (the owner has invited the user, who will be member if he accept the invitation)',
  `addition_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'The date when the user has been invited or has accepted the invitation',
  PRIMARY KEY (`user_id`, `group_id`),
  INDEX `fk_user_has_group_group_1_idx` (`group_id` ASC),
  INDEX `fk_user_has_group_user_1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_group_group_1`
    FOREIGN KEY (`group_id`)
    REFERENCES `halodb`.`group` (`id`),
  CONSTRAINT `fk_user_has_group_users_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `halodb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `halodb`.`publication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `halodb`.`publication` ;

CREATE TABLE IF NOT EXISTS `halodb`.`publication` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titl` VARCHAR(400) NULL DEFAULT NULL COMMENT 'Title',
  `jour` VARCHAR(80) NULL DEFAULT NULL COMMENT 'Journal',
  `volume` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Volume',
  `pages` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Pages',
  `doi` VARCHAR(400) NULL DEFAULT NULL COMMENT 'Publication DOI',
  `sample_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table `halodb`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `halodb`.`author` ;

CREATE TABLE IF NOT EXISTS `halodb`.`author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL,
  `user_id` INT NULL DEFAULT NULL,
  `email` VARCHAR(256) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_authors_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_author_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `halodb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table `halodb`.`publication_has_author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `halodb`.`publication_has_author` ;

CREATE TABLE IF NOT EXISTS `halodb`.`publication_has_author` (
  `author_id` INT NOT NULL,
  `publication_id` INT NOT NULL,
  `coau` BOOLEAN NULL DEFAULT false COMMENT 'The author is a corresponding author of the publication.',
  PRIMARY KEY (`author_id`, `publication_id`),
  INDEX `fk_publication_has_author_samples1_idx` (`publication_id` ASC),
  INDEX `fk_publication_has_author_users1_idx` (`author_id` ASC),
  CONSTRAINT `fk_publication_has_author_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `halodb`.`author` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_publication_has_author_publication1`
    FOREIGN KEY (`publication_id`)
    REFERENCES `halodb`.`publication` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table `halodb`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `halodb`.`project` ;

CREATE TABLE IF NOT EXISTS `halodb`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `description` VARCHAR(400) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table `halodb`.`user_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `halodb`.`user_project` ;

CREATE TABLE IF NOT EXISTS `halodb`.`user_project` (
  `user_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `project_id`),
  INDEX `fk_users_has_projects_projects1_idx` (`project_id` ASC),
  INDEX `fk_users_has_projects_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_project_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `halodb`.`user` (`id`),
  CONSTRAINT `fk_users_has_projects_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `halodb`.`project` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
